version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cryptoview-postgres
    environment:
      POSTGRES_DB: crypto_dashboard
      POSTGRES_USER: cryptoview
      POSTGRES_PASSWORD: cryptoview_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cryptoview"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: cryptoview-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
  redis_data:
